---
layout: cv
title: Thomas Meilstrup's CV
---
# Thomas Meilstrup
Bioinformatician and Musician.

## Currently

Intern at BYU studying respiratory diseases with Chantel Sloan-Aagard

### Skills

Social Media Management. Computer Skills – Introductory Python, R, & SQL. Capable Leader and Teacher. Quick Learner. Researcher


### Research interests

Genetics, Molecular Biology, Biochemistry.


## Education

`Fall 2017 - Spring 2021`
__Chaparral High School – Parker, CO__

`FALL 2021 – SPRING 2022, Fall 2024 -- PRESENT  `
__Brigham Young University - Idaho – Rexburg, ID__

- Currently Majoring in Biology with an Emphasis in Bioinformatics.

- Member of the PhD Research Honor Society.

- Participating in an extracurricular research team doing PCR diagnostics for metabolic syndrome and Least Chub range testing.


## Awards

__Boy Scouts__

`2017`
Eagle Scout

__Chaparral Band__

`2021`
- John Philip Sousa Band Award
- Senior Outstanding Band Student
- Outstanding Citizenship Award



## Work and Volunteer Experiece

<!-- A list is also available [online](http://scholar.google.co.uk/citations?user=LTOTl0YAAAAJ) -->

### Dairy Queen – Cashier
`JUNE 2024 – SEPTEMBER 2024`
Managed drive-through transactions.  Assisted in closing most nights.

### California, San Diego Mission – Social Media Leader
`MAY 2023 – MAY 2024`
Led and Managed social media teams while a volunteer missionary. Teams included Analytics, Graphic Design, Messaging, Video Production, and others.

### Church of Jesus Christ of Latter-day Saints – Missionary
`MAY 2022 – MAY 2024`
Effectively provided humanitarian assistance and training to several thousand people over a two-year period in San Diego CA.

### Regal Cinemas – Floor Staff
`SPRING 2021 – SPRING 2022`
Cleaned movie theatres, sold concessions and tickets.

### HoneyBaked Ham Co. – Crew Member
`DECEMBER 2019`
Seasonal job wrapping, facing, and weighing hams and turkeys

### King Soopers – Courtesy Clerk
`JUNE 2019 – AUGUST 2019`
Bagged Groceries, Faced Shelves, Gathered carts

### Stonegate Pool – Snack Shack
`SUMMER 2017 – SUMMER 2021`
Staffed the snack shack at the pool on a volunteer basis each summer as a fundraiser for the Chaparral Marching Band.

### Douglas County Libraries – Teen Library Council 
`SPRING 2016 – SPRING 2021`
Planned, executed, and hosted various library events each month.

### CHEIM Elementary Band Camp -- Director’s Assistant
`SUMMER 2015 – SUMMER 2019`
Led sectionals for elementary students at a weeklong camp every year.


<!-- ### Footer

Last updated: April 2025 -->